backend:
  name: git-gateway
  branch: Dynamic

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "test_content"
    label: "Test Content"
    files:
      - name: "site_content"
        label: "Site Content"
        file: "data/site-content.json"
        format: "json"
        fields:
          - label: "Meta"
            name: "meta"
            widget: "object"
            fields:
              - { label: "Title", name: "title", widget: "string" }
